### ISSUE TITLE
Only replaces the first reference

### ISSUE THREAD

**Issue by valplusplusle** [eneko89/cachekill#1]
First of all thanks for the time you spent in this project. It really fits my needs at the moment:)

When i use the tool and use one reference on two points, it always changes only the first one.
(So when i have 1 picture that i call on two places of the page, the link in the is css only search and replaced by one of them.
So 1 picture still links to the old name)
In the documentation of "replace-in-file" they talk about a regex which is need: https://www.npmjs.com/package/replace-in-file#replace-all-occurrences
Would be in line 129 of your code if i am correct.

**Comment by eneko89** [comment]
Yes, this is a bug.

Will push a fix tomorrow, thanks for the feedback 🙂

**Comment by eneko89** [comment]
Fixed in v3.0.2.
